"""Downstream model operations — evaluate / export / package / infer /
model import (build step 11; 13 §11, §6.7–§6.10, 12 §15.3–§15.4).

All five are pluggable-harness surfaces (12 §12.4): the identity,
contract, comparability, and fail-closed machinery is real; the
measurement / execution / format-binary ENGINES are real by default
(`mlforge.ops.engines` — family engines over the model's own weights).
The deterministic scaffolds remain behind the same `MLFORGE_HARNESS=1`
opt-in as `ScaffoldTrainer` — honest harness code for system tests,
labeled `harness: scaffold`, never deliverables.
"""

from mlforge.ops.bundle import (
    BUNDLE_SCHEMA,
    BUNDLES_DIR,
    build_bundle,
    component_integrity,
    list_bundles,
    load_bundle,
    write_bundle,
)
from mlforge.ops.engines import (
    availability_error as engine_availability_error,
    build_engine,
    harness_active,
    load_weights,
    registered_models as registered_engine_models,
)
from mlforge.ops.evaluation import (
    DEFAULT_METRIC_NAMES,
    DEFAULT_PROTOCOL,
    EVALUATIONS_DIR,
    EVALUATION_SCHEMA,
    build_evaluation,
    build_protocol,
    comparability_groups,
    evaluation_dir,
    harness_code_hash,
    latest_evaluation,
    list_evaluations,
    load_evaluation,
    model_entry_hash,
    protocol_hash,
    scaffold_metrics,
    source_tree_hash,
    write_evaluation,
)
from mlforge.ops.exporting import (
    EXPORTS_DIR,
    EXPORT_SCHEMA,
    FORMATS,
    SCAFFOLD_GRAPH_OPS,
    build_export,
    contract_source_dir,
    export_dir,
    latest_export,
    list_exports,
    load_export,
    load_model_spec,
    numerical_validation,
    required_operators,
    scaffold_contract,
    validate_export,
    write_export,
)
from mlforge.ops.importing import SPEC_FILE, WEIGHTS_FILE, read_package
from mlforge.ops.infer import (
    IMAGE_EXTENSIONS,
    OUTPUTS_DIR,
    OUTPUT_SCHEMA,
    check_input,
    execute_engine,
    execute_scaffold,
    load_output,
    output_dir,
    write_output,
)

__all__ = [
    "BUNDLE_SCHEMA",
    "BUNDLES_DIR",
    "DEFAULT_METRIC_NAMES",
    "DEFAULT_PROTOCOL",
    "EVALUATIONS_DIR",
    "EVALUATION_SCHEMA",
    "EXPORTS_DIR",
    "EXPORT_SCHEMA",
    "FORMATS",
    "IMAGE_EXTENSIONS",
    "OUTPUTS_DIR",
    "OUTPUT_SCHEMA",
    "SCAFFOLD_GRAPH_OPS",
    "SPEC_FILE",
    "WEIGHTS_FILE",
    "build_bundle",
    "build_engine",
    "build_evaluation",
    "build_export",
    "build_protocol",
    "check_input",
    "comparability_groups",
    "component_integrity",
    "contract_source_dir",
    "engine_availability_error",
    "evaluation_dir",
    "execute_engine",
    "execute_scaffold",
    "export_dir",
    "harness_active",
    "harness_code_hash",
    "latest_evaluation",
    "latest_export",
    "list_bundles",
    "list_evaluations",
    "list_exports",
    "load_bundle",
    "load_evaluation",
    "load_export",
    "load_model_spec",
    "load_output",
    "load_weights",
    "model_entry_hash",
    "numerical_validation",
    "output_dir",
    "protocol_hash",
    "read_package",
    "registered_engine_models",
    "required_operators",
    "scaffold_contract",
    "scaffold_metrics",
    "source_tree_hash",
    "validate_export",
    "write_bundle",
    "write_evaluation",
    "write_export",
    "write_output",
]
